### 异常类

#### Throwable

所有异常类都有一个共同的父类**Throwable,**它有四个public构造方法

        1.     public Throwable()
        2.     public Throwable(String message)
        3.     public Throwable(String message, Throwable cause)
        4.     public Throwable(Throwable cause)

Throwable类有两个主要参数：一个是message，表示异常消息；另一个是cause，表示触发该异常的其他异常。异常可以形成一个异常链，上层的异常由底层异常触发，cause表示底层异常

#### 异常类体系

![](https://cdn.nlark.com/yuque/0/2022/png/25651796/1669556899190-b072736d-5a8c-4345-ab3a-ff5524d1865c.png)Error表示系统错误或资源耗尽，由Java系统自己使用，应用程序不应抛出和处理，比如图6-1中列出的虚拟机错误（VirtualMacheError）及其子类内存溢出错误（OutOfMemory-Error）和栈溢出错误（StackOverflowError）。

Exception表示应用程序错误，它有很多子类，应用程序也可以通过继承Exception或其子类创建自定义异常。RuntimeException比较特殊，它的名字有点误导，因为其他异常也是运行时产生的，它表示的实际含义是**未受检异常（unchecked exception）**，相对而言，Exception的其他子类和Exception自身则是受检异常（checked exception）,Error及其子类也是未受检异常。

受检（checked）和未受检（unchecked）的区别在于Java如何处理这两种异常。对于受检异常，Java会强制要求程序员进行处理，否则会有编译错误，而对于未受检异常则没有这个要求。

#### 自定义异常

除了Java API中定义的异常类，也可以自己定义异常类，一般是继承Exception或者它的某个子类。如果父类是RuntimeException或它的某个子类，则自定义异常也是未受检异常；如果是Exception或Exception的其他子类，则自定义异常是受检异常。

### 异常处理

#### catch匹配

异常处理机制将根据抛出的异常类型找第一个匹配的catch块，找到后，执行catch块内的代码，不再执行其他catch块，如果没有找到，会继续到上层方法中查找。

        try{
            //可能触发异常的代码
        }catch(NumberFormatException e){
            System.out.println("not valid number");
        }catch(RuntimeException e){
            System.out.println("runtime exception "+e.getMessage());
        }catch(Exception e){
            e.printStackTrace();
        }

#### 重新抛出异常

在catch块内处理完后，可以重新抛出异常，异常可以是原来的，也可以是新建的，如下所示

        try{
            //可能触发异常的代码
        }catch(NumberFormatException e){
            System.out.println("not valid number");
            throw new AppException("输入格式不正确", e);
        }catch(Exception e){
            e.printStackTrace();
            throw e;
        }

#### try-with-resources

使用完资源之后会自动关闭

  

        public static void useResource() throws Exception {
              try(AutoCloseable r = new FileInputStream("hello")) { //创建资源
                  //使用资源
              }
        }

#### throws

异常机制中，还有一个和throw很像的关键字throws，用于声明一个方法可能抛出的异常，语法如下所示：

        public void test() throws AppException,
            SQLException, NumberFormatException {
            //主体代码
        }